# Generated by Django 4.2.5 on 2023-09-11 14:07

from django.db import migrations, models
import task2.models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[task2.models.name_validate]),
        ),
    ]
